POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbHp1Z2UiLCJpZCI6IjVmOTczZmYxODdiOTg5MDUyMGIwODRlNCIsImlhdCI6MTYwMzc0OTIwNX0.HovUYmYPLFlaWURG9yii457FsD_iAmOS3Nid4SbP-Nk

{
    "content": "Token autentikaatiota",
    "important": true,
    "userId": "5f973ff187b9890520b084e4"

}